name: Build Main Branch
on:
  push:
    branches:
    - main
env:
  DOTNET_VERSION: 7.0
jobs:
  build_api:
    name: build api AnggapSajaTest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup Dotnet SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install depedency
      run: dotnet restore
    - name: Build Api
      run: |
        cd AnggapSajaApi
        dotnet build --configuration Release --no-restore
  testing:
    name: testing AnggapSajaAPi
    runs-on: ubuntu-latest
    needs: [build_api]
    steps:
      - name:  Do testing
        run: |
          cd AnggapSajaTest
          dotnet test --no-restore --verbosity normal
